Repository wttech/cogboard, pull requests merged in 2020-02, with the labels that each got.

#248 #235 | Endpoints and Credentials fields can be now cleared
  cogboard-webapp/src/components/EditEndpoint.js
  cogboard-webapp/src/components/widgets/dialogFields/Credentialnput.js
  cogboard-webapp/src/components/widgets/dialogFields/EndpointInput.js
  cogboard-webapp/src/components/widgets/dialogFields/index.js
  cogboard-webapp/src/constants/index.js
  functional/cypress-tests/cypress/fixtures/credentialsEndpoints.js
  functional/cypress-tests/cypress/integration/credentials.js
  functional/cypress-tests/cypress/integration/credentialsEndpoints.js
  functional/cypress-tests/cypress/integration/endpoints.js
  functional/cypress-tests/cypress/integration/settings.js
  functional/cypress-tests/cypress/support/credential.js
  functional/cypress-tests/cypress/support/credentialsEndpoints.js
  functional/cypress-tests/cypress/support/endpoint.js
Labels: bug

#243 #286 | New version notification
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/CogboardConstants.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/ConfigType.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/VersionController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/handler/VersionHandler.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/model/Version.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/service/VersionService.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/validation/version/VersionValidator.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/http/HttpClient.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/security/LoginHandler.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/storage/VolumeStorage.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/storage/VolumeStorageFactory.kt
  cogboard-app/src/main/resources/META-INF/services/io.knotx.server.api.handler.RoutingHandlerFactory
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/config/service/VersionServiceTest.kt
  cogboard-webapp/package.json
  cogboard-webapp/src/App.js
  cogboard-webapp/src/actions/actionCreators.js
  cogboard-webapp/src/actions/helpers.js
  cogboard-webapp/src/actions/thunks.js
  cogboard-webapp/src/actions/types.js
  cogboard-webapp/src/components/NewVersionButtons/helpers.js
  cogboard-webapp/src/components/NewVersionButtons/index.js
  cogboard-webapp/src/components/SnackbarVariantContent/index.js
  cogboard-webapp/src/components/SnackbarWithVariant.js
  cogboard-webapp/src/constants/index.js
  cogboard-webapp/src/reducers/notifications/index.js
  cogboard-webapp/src/reducers/notifications/isWaitingForNewVersion.js
  cogboard-webapp/src/selectors/index.js
  gradle/docker.gradle.kts
  knotx/conf/cogboard.conf
  knotx/conf/openapi.yaml
  knotx/conf/routes/operations.conf
  mnt/.version
Labels: enhancement

#252 Regexp fix for Jenkins job automation test (locale)
  functional/cypress-tests/cypress/support/widgetAssertions.js
Labels: bug

#254 Release will publish Docker Hub images
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release_version.yml
  build.gradle.kts
  cogboard-compose.yml
  gradle/prepareCogboardCompose.gradle.kts
  scripts/dev_build.sh
  scripts/release.sh
Labels: enhancement

#257 Removing unnecessary command from GitHub workflow
  .github/workflows/release-drafter.yml
Labels: maintenance
