Repository wttech/cogboard, pull requests merged in 2020-01, with the labels that each got.

#208 bugfix/registering-multiple-subscribers
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/BaseWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/CheckboxWidget.kt
Labels: bug

#155 feature/CLAN6-43--widget-person-draw
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/WidgetIndex.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/persondraw/PersonDrawUtils.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/persondraw/PersonDrawWidget.kt
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/widget/type/persondraw/PersonDrawUtilsTest.kt
  cogboard-webapp/src/components/widgets/dialogFields/MultiTextInput.js
  cogboard-webapp/src/components/widgets/dialogFields/helpers.js
  cogboard-webapp/src/components/widgets/dialogFields/index.js
  cogboard-webapp/src/components/widgets/index.js
  cogboard-webapp/src/components/widgets/types/PersonDrawWidget/index.js
  cogboard-webapp/src/components/widgets/types/PersonDrawWidget/styled.js
  docs/widget-persondraw-text.md
  functional/cypress-tests/cypress/fixtures/credentialsEndpoints.js
  functional/cypress-tests/cypress/integration/credentialsEndpoints.js
  functional/cypress-tests/cypress/support/credentialsEndpoints.js
  functional/cypress-tests/cypress/support/user.js
Labels: enhancement

#215 Release drafter workflow and github release features
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release_version.yml
  .travis.yml
  CONTRIBUTING.md
  build.gradle.kts
  cogboard-compose.yml
  cogboard.zip
  gradle.properties
  gradle/release.gradle
Labels: enhancement

#227 Person Draw improvements
  cogboard-webapp/src/components/widgets/dialogFields/MultiTextInput.js
  cogboard-webapp/src/components/widgets/dialogFields/styled.js
  cogboard-webapp/src/components/widgets/types/PersonDrawWidget/index.js
  cogboard-webapp/src/components/widgets/types/PersonDrawWidget/styled.js
Labels: bug

#218 feature/CLAN6-291-fallback-missing-widget
  cogboard-webapp/src/components/Widget/index.js
Labels: bug

#228 #43 Switch to io.knotx.distribution plugin instead of built script
  build.gradle.kts
  cogboard-webapp/build.gradle.kts
  docker/Dockerfile
  gradle.properties
  gradle/distribution.gradle.kts
  gradle/docker.gradle.kts
Labels: enhancement

#226 #153 | Widget automated tests fixed and refactored
  functional/cypress-tests/cypress/fixtures/Widgets.js
  functional/cypress-tests/cypress/integration/widgets.js
  functional/cypress-tests/cypress/support/widget.js
  functional/cypress-tests/cypress/support/widgetAssertions.js
  functional/cypress-tests/cypress/support/widgetDynamicTab.js
Labels: bug

#229 Sonarqube 6.x added, works exactly the same way 7.x does.
  cogboard-webapp/src/constants/index.js
  functional/cypress-tests/cypress/fixtures/Widgets.js
Labels: enhancement

#240 Prettier plugin added to Cypress tests
  functional/cypress-tests/.prettierrc
  functional/cypress-tests/README.md
  functional/cypress-tests/cypress/fixtures/Dashboard.js
  functional/cypress-tests/cypress/fixtures/credentialsEndpoints.js
  functional/cypress-tests/cypress/integration/credentialsEndpoints.js
  functional/cypress-tests/cypress/integration/dashboards.js
  functional/cypress-tests/cypress/integration/login.js
  functional/cypress-tests/cypress/integration/logout.js
  functional/cypress-tests/cypress/integration/reordering.js
  functional/cypress-tests/cypress/integration/saving.js
  functional/cypress-tests/cypress/integration/widgets.js
  functional/cypress-tests/cypress/support/commands.js
  functional/cypress-tests/cypress/support/credentialsEndpoints.js
  functional/cypress-tests/cypress/support/dashboards.js
  functional/cypress-tests/cypress/support/helpers.js
  functional/cypress-tests/cypress/support/reorder.js
  functional/cypress-tests/cypress/support/user.js
  functional/cypress-tests/cypress/support/widget.js
  functional/cypress-tests/cypress/support/widgetAssertions.js
  functional/cypress-tests/cypress/support/widgetDynamicTab.js
  functional/cypress-tests/cypress/support/widgets.js
  functional/cypress-tests/package.json
Labels: maintenance

#241 Dashboard tests refactored and updated
  functional/cypress-tests/cypress/fixtures/Dashboard.js
  functional/cypress-tests/cypress/integration/dashboards.js
  functional/cypress-tests/cypress/support/dashboard.js
  functional/cypress-tests/cypress/support/dashboards.js
Labels: maintenance

#242 #234 | Better URL validation | Iframe board tests added (plus some refactor)
  .github/PULL_REQUEST_TEMPLATE.md
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/ControllerFactory.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/persondraw/PersonDrawUtils.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/sonarqube/SonarQubeWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/sonarqube/Version.kt
  cogboard-webapp/src/components/widgets/dialogFields/index.js
  functional/cypress-tests/cypress/fixtures/Dashboard.js
  functional/cypress-tests/cypress/integration/dashboards.js
  functional/cypress-tests/cypress/support/dashboard.js
  functional/cypress-tests/cypress/support/dashboards.js
Labels: maintenance

#245 #244 | Unable to add endpoint
  cogboard-webapp/src/components/widgets/dialogFields/index.js
  functional/cypress-tests/cypress/integration/credentialsEndpoints.js
Labels: bug
