Repository wttech/cogboard, pull requests merged in 2020-10, with the labels that each got.

#282 Release v.1.0.0 preparation
  .github/workflows/release-drafter.yml
  gradle.properties
Labels: maintenance

#280 Bugfix | Person Draw - fix positive values & daily refresh
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/randompicker/RandomPickerUtils.kt
  cogboard-webapp/src/components/widgets/dialogFields/index.js
  cogboard-webapp/src/components/widgets/index.js
Labels: bug

#281 Styling | More consistent button behavior in main menu
  cogboard-webapp/src/components/AddBoard.js
  cogboard-webapp/src/components/AddButton.js
  cogboard-webapp/src/components/AddItem.js
  cogboard-webapp/src/components/BoardActions/styled.js
  cogboard-webapp/src/components/BoardActions/types/Add.js
  cogboard-webapp/src/components/BoardActions/types/Save.js
  cogboard-webapp/src/components/BoardCard/index.js
  cogboard-webapp/src/components/BoardSwitcher/index.js
  cogboard-webapp/src/components/DeleteItem.js
  cogboard-webapp/src/components/EditCredential.js
  cogboard-webapp/src/components/EditEndpoint.js
  cogboard-webapp/src/components/NavBar.js
  cogboard-webapp/src/components/SettingsMenu/index.js
  cogboard-webapp/src/components/UserLogin/index.js
  cogboard-webapp/src/components/styled/index.js
  cogboard-webapp/src/components/widgets/dialogFields/JiraBucketsInput.js
  cogboard-webapp/src/components/widgets/dialogFields/LinkListInput.js
  cogboard-webapp/src/components/widgets/dialogFields/MultiTextInput.js
  cogboard-webapp/src/components/widgets/dialogFields/ToDoListinput.js
Labels: enhancement

#283 Sonarqube Widget - token authentication support
  api-mocks/__files/zabbix/uptime.json
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/CogboardConstants.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/http/HttpClient.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/http/auth/AuthenticationFactory.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/http/auth/AuthenticationType.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/AsyncWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/JenkinsJobWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/ServiceCheckWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/sonarqube/SonarQubeWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/zabbix/ZabbixWidget.kt
  cogboard-webapp/src/components/CredentialForm/index.js
  cogboard-webapp/src/components/widgets/dialogFields/MultilineTextInput.js
  cogboard-webapp/src/components/widgets/dialogFields/index.js
  cogboard-webapp/src/components/widgets/dialogFields/styled.js
  cogboard-webapp/src/components/widgets/types/ZabbixWidget/index.js
  cogboard-webapp/src/components/widgets/types/ZabbixWidget/styled.js
  cogboard-webapp/src/constants/index.js
  docs/images/CredentailChange.png
  functional/cypress-tests/cypress/fixtures/credentialsEndpoints.js
  functional/cypress-tests/cypress/integration/credentials.js
  functional/cypress-tests/cypress/support/credential.js
Labels: enhancement

#303 Initial configs updated with new widgets
  cogboard-app/src/main/resources/initData/admin.json
  cogboard-app/src/main/resources/initData/config.json
  cogboard-app/src/main/resources/initData/credentials.json
  cogboard-app/src/main/resources/initData/endpoints.json
  functional/cypress-tests/cypress/integration/refresh_widgets.js
Labels: maintenance

#311 Bugfix | Zabbix Widget - allow only numbers for max value
  cogboard-webapp/src/components/widgets/dialogFields/MaxValueInput.js
  cogboard-webapp/src/components/widgets/types/ZabbixWidget/index.js
Labels: bug

#308 Styling | Rearrange Icons - and other fixes
  .gitignore
  cogboard-webapp/src/components/ErrorMessage.js
  cogboard-webapp/src/components/LastUpdate/index.js
  cogboard-webapp/src/components/LastUpdate/styled.js
  cogboard-webapp/src/components/Widget/styled.js
  cogboard-webapp/src/components/WidgetFooter.js
Labels: enhancement
