Repository wttech/cogboard, pull requests merged in 2020-08, with the labels that each got.

#267 Feature/token support for logging into 3rd party services
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/CogboardConstants.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/CredentialsConfig.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/EndpointLoader.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/EndpointsConfig.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/CredentialsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/model/Credential.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/http/HttpClient.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/AsyncWidget.kt
  cogboard-app/src/main/resources/initData/credentials.json
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/config/EndpointTest.kt
  cogboard-app/src/test/resources/com/cognifide/cogboard/config/credentials-test.json
  cogboard-webapp/src/components/CredentialForm/index.js
  cogboard-webapp/src/components/EditCredential.js
  cogboard-webapp/src/components/widgets/dialogFields/index.js
  cogboard-webapp/src/constants/index.js
  docs/images/docker-windows-config.png
  docs/images/docker-windows-config2.png
  functional/cypress-tests/cypress/fixtures/credentialsEndpoints.js
  functional/cypress-tests/cypress/integration/credentials.js
  functional/cypress-tests/cypress/support/credential.js
Labels: enhancement

#269 Form and widget more menu styling improvements
  cogboard-webapp/src/components/MoreMenu/index.js
  cogboard-webapp/src/components/MoreMenu/styled.js
  cogboard-webapp/src/components/UserLogin/index.js
  cogboard-webapp/src/components/styled/index.js
Labels: enhancement

#270 Defect/update credentials doesnt work properly
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/CogboardConstants.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/CredentialsConfig.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/EndpointsConfig.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/BoardsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/ControllerFactory.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/CredentialsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/EndpointsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/WidgetsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/handler/ConfigApiHandler.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/service/WidgetRuntimeService.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/utils/JsonUtils.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/BaseWidget.kt
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/widget/type/BambooDeploymentWidgetTest.kt
  functional/cypress-tests/cypress/integration/refresh_widgets.js
  knotx/conf/cogboard.conf
  knotx/conf/routes/operations.conf
Labels: bug

#271 Cypress Updated
  functional/cypress-tests/package.json
Labels: maintenance
