Repository wttech/cogboard, pull requests merged in 2021-04, with the labels that each got.

#357 General | Refresh every APP state after save event
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/CogboardConstants.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/CredentialsConfig.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/EndpointLoader.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/EndpointsConfig.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/BoardsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/ConfirmationSender.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/CredentialsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/EndpointsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/UserController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/VersionController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/WidgetsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/handler/VersionHandler.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/helper/EntityCleanupHelper.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/service/BoardsConfigService.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/service/UserService.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/service/WidgetRuntimeService.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/validation/boards/BoardsValidator.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/http/HttpClient.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/http/WebSocketsServer.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/security/LoginHandler.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/security/SessionHandler.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/utils/ExtensionFunctions.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/AsyncWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/BaseWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/WidgetIndex.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/handler/ContentUpdateWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/handler/DeleteWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/handler/UpdateWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/AemBundleInfoWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/AemHealthcheckWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/BambooDeploymentWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/BambooPlanWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/JenkinsJobWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/JiraBucketsWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/ServiceCheckWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/randompicker/RandomPickerWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/sonarqube/SonarQubeWidget.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/zabbix/ZabbixWidget.kt
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/config/storage/VolumeStorageTest.kt
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/widget/WidgetIndexTest.kt
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/widget/type/BambooDeploymentWidgetTest.kt
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/widget/type/WidgetTestBase.kt
  cogboard-webapp/src/App.js
  cogboard-webapp/src/actions/actionCreators.js
  cogboard-webapp/src/actions/thunks.js
  cogboard-webapp/src/actions/types.js
  cogboard-webapp/src/constants/index.js
  cogboard-webapp/src/reducers/app/index.js
  cogboard-webapp/src/reducers/app/requiresRefetching.js
  cogboard-webapp/src/reducers/boards/allBoards.js
  detekt.yml
Labels: enhancement

#358 #344 | Text widget vertical mode fixes
  cogboard-webapp/src/components/widgets/types/TextWidget/index.js
Labels: bug

#360 Readme update
  README.md
  docs/images/Cogboard.png
  docs/images/cogboard-1.png
  docs/images/cogboard-2.png
  docs/images/cogboard-3.png
Labels: maintenance

#363 Switch CI from Travis to GitHub actions
  .github/workflows/ci.yml
  .travis.yml
Labels: maintenance

#359 #288 | Orderable todo list
  cogboard-webapp/package-lock.json
  cogboard-webapp/package.json
  cogboard-webapp/src/components/widgets/dialogFields/JiraBucketsInput.js
  cogboard-webapp/src/components/widgets/dialogFields/LinkListInput.js
  cogboard-webapp/src/components/widgets/dialogFields/MultiTextInput.js
  cogboard-webapp/src/components/widgets/dialogFields/ToDoListinput.js
  cogboard-webapp/src/components/widgets/dialogFields/helpers.js
Labels: enhancement

#366 Project stack update
  build.gradle.kts
  buildSrc/build.gradle.kts
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/sonarqube/SonarQubeWidget.kt
  cogboard-webapp/build.gradle.kts
  detekt.yml
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: maintenance

#367 Release 1.0.5 preparation
  gradle.properties
Labels: maintenance

#365 Boards API refactorred
  .gitignore
  .idea/runConfigurations/Build.xml
  .idea/runConfigurations/Debug.xml
  .idea/runConfigurations/Open_Cypress.xml
  .idea/runConfigurations/Run_Tests.xml
  build.gradle.kts
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/BoardsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/ConfirmationSender.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/controller/WidgetsController.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/handler/HandlerUtil.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/model/Board.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/model/Widgets.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/service/BoardsConfigHelper.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/service/BoardsConfigService.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/service/WidgetRuntimeService.kt
  cogboard-app/src/main/kotlin/com/cognifide/cogboard/storage/ContentRepository.kt
  cogboard-app/src/main/resources/cypressData/config.json
  cogboard-app/src/main/resources/initData/config.json
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/config/service/BoardsConfigHelperTest.kt
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/config/service/BoardsConfigServiceTest.kt
  cogboard-app/src/test/kotlin/com/cognifide/cogboard/widget/type/WidgetTestBase.kt
  cogboard-app/src/test/resources/board/config-from-frontend.json
  cogboard-app/src/test/resources/board/config-on-backend.json
  cogboard-app/src/test/resources/com/cognifide/cogboard/config/board-3.json
  cogboard-app/src/test/resources/com/cognifide/cogboard/config/config-with-2-boards.json
  cogboard-webapp/src/actions/actionCreators.js
  cogboard-webapp/src/actions/helpers.js
  cogboard-webapp/src/actions/thunks.js
  cogboard-webapp/src/constants/index.js
  cogboard-webapp/src/reducers/widgets/allWidgets.js
  cogboard-webapp/src/reducers/widgets/index.js
  functional/cypress-tests/cypress/fixtures/Dashboard.js
  functional/cypress-tests/cypress/fixtures/reorderingConfig.json
  functional/cypress-tests/cypress/integration/dashboards.js
  functional/cypress-tests/cypress/integration/reordering_widgets.js
  functional/cypress-tests/cypress/integration/saving.js
  functional/cypress-tests/cypress/support/dashboard.js
  functional/cypress-tests/cypress/support/helpers.js
  knotx/conf/openapi.yaml
  knotx/conf/routes/operations.conf
Labels: enhancement, not ready
